### ISSUE TITLE
Only works with tmux v2.1 and later

### ISSUE THREAD

**Issue by ryanerwin** [wookayin/is_mosh#1]
Prior to [tmux v2.1](https://github.com/tmux/tmux/commit/29c29e771767b037f2929b889bb0de2b0b6ee138), there wasn't a `client_pid` format option...
Would probably be good to add a check for the Tmux version number as some distros (looking at you RHEL/CentOS) ship ancient version of Tmux even on relatively recent releases...

```
commit 29c29e771767b037f2929b889bb0de2b0b6ee138   refs/tags/2.1
Author: nicm <nicm>
Date:   Sun Jun 14 10:07:44 2015 +0000

    Add a format for client PID (client_pid) and server PID (pid). Diff for
    client_pid from Thomas Adam.
```

I thought there was a logical error in the program, but after some digging realized it was just that a particular system's tmux was older than 2.1, so `tmux list-clients -F '#{client_pid}'` was returning a blank value...

**Comment by wookayin** [comment]
To the current best of my knowledge I cannot find alternative ways to get client's PID. Looking at https://github.com/tmux/tmux/commit/29c29e771767b037f2929b889bb0de2b0b6ee138, it seems there is no way to obtain client's pid before this commit. I mentioned this issue in README.

**Comment by wookayin** [comment]
tmux 2.0 is outdated and the modern versions of mosh now supports 24-bit color well (so no longer `is_mosh` required), so we can close the issue. Thanks!
